// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkFHWi7GGfLRwmqTG0fMBX-2uyePhvKY',
    appId: '1:1026638132626:web:f6f4c4dd9d2345d062bd4b',
    messagingSenderId: '1026638132626',
    projectId: 'coffee-df5fe',
    authDomain: 'coffee-df5fe.firebaseapp.com',
    storageBucket: 'coffee-df5fe.firebasestorage.app',
    measurementId: 'G-9YEMTM1T99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLXFX7ARTXWyvaIQvhnTboDsgbYdUZfTw',
    appId: '1:1026638132626:android:ac55c5d90fb7c41362bd4b',
    messagingSenderId: '1026638132626',
    projectId: 'coffee-df5fe',
    storageBucket: 'coffee-df5fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwO1HdBxez1_zoOEE9wtGaU4Pf4-Oi1ck',
    appId: '1:1026638132626:ios:8912665807e007f562bd4b',
    messagingSenderId: '1026638132626',
    projectId: 'coffee-df5fe',
    storageBucket: 'coffee-df5fe.firebasestorage.app',
    iosBundleId: 'com.example.fireb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwO1HdBxez1_zoOEE9wtGaU4Pf4-Oi1ck',
    appId: '1:1026638132626:ios:8912665807e007f562bd4b',
    messagingSenderId: '1026638132626',
    projectId: 'coffee-df5fe',
    storageBucket: 'coffee-df5fe.firebasestorage.app',
    iosBundleId: 'com.example.fireb',
  );
}
